name: Auto Update Xoiche M3U Playlist

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Khóa phiên bản 3.11 ổn định nhất

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper

      - name: Generate M3U File
        run: python -u generate_m3u.py # Thêm -u để hiển thị log trực tiếp

      - name: Commit and Push update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add xoiche.m3u
          git diff-index --quiet HEAD || (git commit -m "Auto-update playlist [skip ci]" && git push)
          
